import {
  Binary,
  Bomb,
  BookKey,
  Braces,
  CalendarClock,
  FileKey2,
  Globe,
  KeyRound,
  QrCode,
  ScanText,
  Shield,
  Smile,
} from 'lucide-react'
import { lazy } from 'react'

import type { ToolDefinition } from '@/types/tool'

export const tools: ToolDefinition[] = [
  {
    id: 'json-format',
    name: 'JSON 格式化',
    description: '格式化、压缩与校验 JSON 文本',
    path: '/json-format',
    category: 'format',
    keywords: ['json', 'format', 'beautify', 'minify'],
    icon: Braces,
    component: lazy(() => import('@/tools/json-format')),
  },
  {
    id: 'detect-delimiter',
    name: '分隔符识别',
    description: '从样例文本智能识别分隔符并预览拆分结果',
    path: '/detect-delimiter',
    category: 'text',
    keywords: [
      'delimiter',
      'separator',
      'csv',
      'tsv',
      'split',
      '分隔符',
      '逗号',
      '制表符',
    ],
    icon: ScanText,
    component: lazy(() => import('@/tools/detect-delimiter')),
  },
  {
    id: 'text-bang',
    name: '文字大爆炸',
    description: 'jieba 或分隔符打散文本，点词即可复制',
    path: '/text-bang',
    category: 'text',
    keywords: [
      'jieba',
      'segment',
      'tokenize',
      'delimiter',
      'csv',
      '分词',
      '分隔符',
      '大爆炸',
      'smartisan',
      '锤子',
    ],
    icon: Bomb,
    component: lazy(() => import('@/tools/text-bang')),
  },
  {
    id: 'diceface',
    name: 'DiceFace',
    description: '从任意字符串生成唯一、可复现的哈希头像',
    path: '/diceface',
    category: 'other',
    keywords: ['avatar', 'dicebear', 'hash', '头像', 'identicon'],
    icon: Smile,
    component: lazy(() => import('@/tools/diceface')),
  },
  {
    id: 'public-ip',
    name: '外网 IP',
    description: '查询当前设备的出口公网 IP',
    path: '/public-ip',
    category: 'other',
    keywords: ['ip', 'public', '外网', '公网', 'ipify'],
    icon: Globe,
    component: lazy(() => import('@/tools/public-ip')),
  },
  {
    id: 'qr-code',
    name: '二维码生成',
    description: '将文本或链接生成本地二维码',
    path: '/qr-code',
    category: 'convert',
    keywords: ['qr', 'qrcode', '二维码', 'barcode'],
    icon: QrCode,
    component: lazy(() => import('@/tools/qr-code')),
  },
  {
    id: 'otp',
    name: 'OTP 生成器',
    description: '本地生成 TOTP 验证码与 otpauth URI',
    path: '/otp',
    category: 'other',
    keywords: ['otp', 'totp', '2fa', 'authenticator', '验证码'],
    icon: KeyRound,
    component: lazy(() => import('@/tools/otp')),
  },
  {
    id: 'jwt',
    name: 'JWT 解析',
    description: '本地解码 JWT Header / Payload，查看过期时间',
    path: '/jwt',
    category: 'encode',
    keywords: ['jwt', 'token', 'decode', 'base64', '鉴权'],
    icon: FileKey2,
    component: lazy(() => import('@/tools/jwt')),
  },
  {
    id: 'base-convert',
    name: '进制转换',
    description: '在 2–36 进制之间转换整数',
    path: '/base-convert',
    category: 'convert',
    keywords: ['base', 'binary', 'hex', 'octal', '进制', '二进制', '十六进制'],
    icon: Binary,
    component: lazy(() => import('@/tools/base-convert')),
  },
  {
    id: 'datetime',
    name: '日期时间转换',
    description: 'Unix 时间戳与 ISO / 本地时间互转',
    path: '/datetime',
    category: 'convert',
    keywords: [
      'datetime',
      'timestamp',
      'unix',
      'iso',
      'date',
      'time',
      '时间戳',
      '日期',
      '时区',
    ],
    icon: CalendarClock,
    component: lazy(() => import('@/tools/datetime')),
  },
  {
    id: 'bcrypt',
    name: 'Bcrypt',
    description: '本地生成 Bcrypt 哈希并比对明文',
    path: '/bcrypt',
    category: 'encode',
    keywords: ['bcrypt', 'hash', 'password', 'salt', '加密', '比对'],
    icon: Shield,
    component: lazy(() => import('@/tools/bcrypt')),
  },
  {
    id: 'bip39',
    name: 'BIP39 助记词',
    description: '本地生成/校验助记词，派生多链钱包地址',
    path: '/bip39',
    category: 'other',
    keywords: [
      'bip39',
      'mnemonic',
      'seed',
      'wallet',
      'ethereum',
      'bitcoin',
      'tron',
      'cosmos',
      '助记词',
      '钱包',
      '地址',
    ],
    icon: BookKey,
    component: lazy(() => import('@/tools/bip39')),
  },
]

export function getToolByPath(path: string) {
  return tools.find((tool) => tool.path === path)
}

export function getToolById(id: string) {
  return tools.find((tool) => tool.id === id)
}
