import {
  ArrowLeftRight,
  Binary,
  Bomb,
  BookKey,
  Braces,
  CalendarClock,
  CaseSensitive,
  CodeXml,
  Database,
  Diff,
  FileKey2,
  Globe,
  Hash,
  Images,
  KeyRound,
  Link2,
  QrCode,
  ScanText,
  Shield,
  Smile,
  Table,
  Table2,
} from 'lucide-react'
import { lazy } from 'react'

import type { ToolDefinition } from '@/types/tool'

export const tools: ToolDefinition[] = [
  {
    id: 'json-format',
    name: 'JSON 格式化',
    description: '格式化、压缩、字段排序与自定义缩进',
    path: '/json-format',
    category: 'format',
    keywords: ['json', 'format', 'beautify', 'minify', 'sort', 'indent', '排序', '缩进'],
    icon: Braces,
    component: lazy(() => import('@/tools/json-format')),
  },
  {
    id: 'xml-format',
    name: 'XML 格式化',
    description: '格式化、压缩 XML，并支持自定义缩进',
    path: '/xml-format',
    category: 'format',
    keywords: ['xml', 'format', 'beautify', 'minify', 'indent', '格式化', '压缩'],
    icon: CodeXml,
    component: lazy(() => import('@/tools/xml-format')),
  },
  {
    id: 'sql-format',
    name: 'SQL 格式化',
    description: '按方言美化 SQL，支持缩进与关键字大小写',
    path: '/sql-format',
    category: 'format',
    keywords: [
      'sql',
      'format',
      'beautify',
      'mysql',
      'postgres',
      'sqlite',
      '格式化',
    ],
    icon: Database,
    component: lazy(() => import('@/tools/sql-format')),
  },
  {
    id: 'data-convert',
    name: '数据格式互转',
    description: 'JSON / YAML / XML / TOML 互相转换',
    path: '/data-convert',
    category: 'convert',
    keywords: [
      'json',
      'yaml',
      'xml',
      'toml',
      'convert',
      'transform',
      '互转',
      '转换',
    ],
    icon: ArrowLeftRight,
    component: lazy(() => import('@/tools/data-convert')),
  },
  {
    id: 'text-count',
    name: '字数统计',
    description: '实时统计字符、汉字、行数与 UTF-8 字节',
    path: '/text-count',
    category: 'text',
    keywords: [
      'count',
      '字符',
      '字数',
      '词数',
      '行数',
      '字节',
      '统计',
      'length',
    ],
    icon: Hash,
    component: lazy(() => import('@/tools/text-count')),
  },
  {
    id: 'text-diff',
    name: '文本 Diff',
    description: '对比两段文本，支持左右对照与统一视图',
    path: '/text-diff',
    category: 'text',
    keywords: [
      'diff',
      'compare',
      'difference',
      '对比',
      '差异',
      'patch',
      '比较',
    ],
    icon: Diff,
    component: lazy(() => import('@/tools/text-diff')),
  },
  {
    id: 'detect-delimiter',
    name: '文本分割',
    description: '按分隔符拆分文本，并预览表格结果',
    path: '/detect-delimiter',
    category: 'text',
    keywords: [
      'delimiter',
      'separator',
      'csv',
      'tsv',
      'split',
      '文本分割',
      '分隔符',
      '逗号',
      '制表符',
    ],
    icon: ScanText,
    component: lazy(() => import('@/tools/detect-delimiter')),
  },
  {
    id: 'text-bang',
    name: '文字大爆炸',
    description: 'jieba 或分隔符打散文本，点词即可复制',
    path: '/text-bang',
    category: 'text',
    keywords: [
      'jieba',
      'segment',
      'tokenize',
      'delimiter',
      'csv',
      '分词',
      '分隔符',
      '大爆炸',
      'smartisan',
      '锤子',
    ],
    icon: Bomb,
    component: lazy(() => import('@/tools/text-bang')),
  },
  {
    id: 'card-poster',
    name: '卡片海报',
    description: 'Markdown 转分享卡片，导出 SVG / PNG',
    path: '/card-poster',
    category: 'other',
    keywords: [
      'markdown',
      'md',
      'svg',
      'png',
      'poster',
      'card',
      '海报',
      '卡片',
      '小红书',
      '朋友圈',
    ],
    icon: Images,
    component: lazy(() => import('@/tools/card-poster')),
  },
  {
    id: 'diceface',
    name: 'DiceFace',
    description: '从任意字符串生成唯一、可复现的哈希头像',
    path: '/diceface',
    category: 'other',
    keywords: ['avatar', 'dicebear', 'hash', '头像', 'identicon'],
    icon: Smile,
    component: lazy(() => import('@/tools/diceface')),
  },
  {
    id: 'public-ip',
    name: '外网 IP',
    description: '查询当前设备的出口公网 IP',
    path: '/public-ip',
    category: 'other',
    keywords: ['ip', 'public', '外网', '公网', 'ipify'],
    icon: Globe,
    component: lazy(() => import('@/tools/public-ip')),
  },
  {
    id: 'qr-code',
    name: '二维码生成',
    description: '将文本或链接生成本地二维码',
    path: '/qr-code',
    category: 'convert',
    keywords: ['qr', 'qrcode', '二维码', 'barcode'],
    icon: QrCode,
    component: lazy(() => import('@/tools/qr-code')),
  },
  {
    id: 'otp',
    name: 'OTP 生成器',
    description: '本地生成 TOTP 验证码与 otpauth URI',
    path: '/otp',
    category: 'other',
    keywords: ['otp', 'totp', '2fa', 'authenticator', '验证码'],
    icon: KeyRound,
    component: lazy(() => import('@/tools/otp')),
  },
  {
    id: 'jwt',
    name: 'JWT 解析',
    description: '本地解码 JWT Header / Payload，查看过期时间',
    path: '/jwt',
    category: 'encode',
    keywords: ['jwt', 'token', 'decode', 'base64', '鉴权'],
    icon: FileKey2,
    component: lazy(() => import('@/tools/jwt')),
  },
  {
    id: 'uri-codec',
    name: 'URI 编解码',
    description: 'URI / URI Component 编码与解码',
    path: '/uri-codec',
    category: 'encode',
    keywords: [
      'uri',
      'url',
      'encode',
      'decode',
      'percent',
      '编码',
      '解码',
      '转义',
    ],
    icon: Link2,
    component: lazy(() => import('@/tools/uri-codec')),
  },
  {
    id: 'base-convert',
    name: '进制转换',
    description: '在 2–36 进制之间转换整数',
    path: '/base-convert',
    category: 'convert',
    keywords: ['base', 'binary', 'hex', 'octal', '进制', '二进制', '十六进制'],
    icon: Binary,
    component: lazy(() => import('@/tools/base-convert')),
  },
  {
    id: 'case-convert',
    name: '命名转换',
    description: '驼峰、蛇形、短横线等命名风格互转',
    path: '/case-convert',
    category: 'convert',
    keywords: [
      'case',
      'camel',
      'snake',
      'kebab',
      'pascal',
      '命名',
      '驼峰',
      '蛇形',
      '大小写',
    ],
    icon: CaseSensitive,
    component: lazy(() => import('@/tools/case-convert')),
  },
  {
    id: 'datetime',
    name: '日期时间转换',
    description: 'Unix 时间戳与 ISO / 本地时间互转',
    path: '/datetime',
    category: 'convert',
    keywords: [
      'datetime',
      'timestamp',
      'unix',
      'iso',
      'date',
      'time',
      '时间戳',
      '日期',
      '时区',
    ],
    icon: CalendarClock,
    component: lazy(() => import('@/tools/datetime')),
  },
  {
    id: 'html-to-csv',
    name: 'HTML 转 CSV',
    description: '将 HTML 表格或 ul 列表提取为 CSV',
    path: '/html-to-csv',
    category: 'convert',
    keywords: [
      'html',
      'csv',
      'table',
      'ul',
      'list',
      'extract',
      '表格',
      '列表',
      '转换',
    ],
    icon: Table,
    component: lazy(() => import('@/tools/html-to-csv')),
  },
  {
    id: 'csv-to-html',
    name: 'CSV 转 HTML',
    description: '将 CSV 文本转换为 HTML table 表格',
    path: '/csv-to-html',
    category: 'convert',
    keywords: [
      'csv',
      'html',
      'table',
      'convert',
      '表格',
      '转换',
      'tsv',
    ],
    icon: Table2,
    component: lazy(() => import('@/tools/csv-to-html')),
  },
  {
    id: 'bcrypt',
    name: 'Bcrypt',
    description: '本地生成 Bcrypt 哈希并比对明文',
    path: '/bcrypt',
    category: 'encode',
    keywords: ['bcrypt', 'hash', 'password', 'salt', '加密', '比对'],
    icon: Shield,
    component: lazy(() => import('@/tools/bcrypt')),
  },
  {
    id: 'bip39',
    name: 'BIP39 助记词',
    description: '本地生成/校验助记词，派生多链钱包地址',
    path: '/bip39',
    category: 'other',
    keywords: [
      'bip39',
      'mnemonic',
      'seed',
      'wallet',
      'ethereum',
      'bitcoin',
      'tron',
      'cosmos',
      '助记词',
      '钱包',
      '地址',
    ],
    icon: BookKey,
    component: lazy(() => import('@/tools/bip39')),
  },
]

export function getToolByPath(path: string) {
  return tools.find((tool) => tool.path === path)
}

export function getToolById(id: string) {
  return tools.find((tool) => tool.id === id)
}
